# .github/workflows/main.yml

name: Github Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.ACTIONS.DEPLOY.KEY }}
          source-directory: public
          build-command: npm run deploy
          custom-domain: annagracepennington.com
