# .github/workflows/main.yml

name: Github Pages Publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node Version
        uses: actions/setup-node@v3
      
      - name: Runs deploy
        run: |
          git config --global user.email "${{ secrets.EMAIL}}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/
          npm i
          npm run deploy

